name: coba_richtext
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.3.5
  http: ^1.0.0
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_riverpod: ^2.3.6


flutter:
  uses-material-design: true
